//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentIs is null.
        /// </summary>
        public static string ArgumentIsNull {
            get {
                return ResourceManager.GetString("ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this item because have members.
        /// </summary>
        public static string CanNotDeleteHaveMemebers {
            get {
                return ResourceManager.GetString("CanNotDeleteHaveMemebers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password failed!.
        /// </summary>
        public static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and/or password is not correct!.
        /// </summary>
        public static string ErrorMessage3020_3030 {
            get {
                return ResourceManager.GetString("ErrorMessage3020_3030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not verified!.
        /// </summary>
        public static string ErrorMessage3040 {
            get {
                return ResourceManager.GetString("ErrorMessage3040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active!.
        /// </summary>
        public static string ErrorMessage3050 {
            get {
                return ResourceManager.GetString("ErrorMessage3050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expire time did not specify for this user!.
        /// </summary>
        public static string ErrorMessage3060 {
            get {
                return ResourceManager.GetString("ErrorMessage3060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account expired!.
        /// </summary>
        public static string ErrorMessage3070 {
            get {
                return ResourceManager.GetString("ErrorMessage3070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify user IP!.
        /// </summary>
        public static string ErrorMessage3080 {
            get {
                return ResourceManager.GetString("ErrorMessage3080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP did not defined!.
        /// </summary>
        public static string ErrorMessage3090 {
            get {
                return ResourceManager.GetString("ErrorMessage3090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP is not verified!.
        /// </summary>
        public static string ErrorMessage3100 {
            get {
                return ResourceManager.GetString("ErrorMessage3100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP is not active!.
        /// </summary>
        public static string ErrorMessage3110 {
            get {
                return ResourceManager.GetString("ErrorMessage3110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid!.
        /// </summary>
        public static string IsNotValid {
            get {
                return ResourceManager.GetString("IsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed! Username or password is invalid!.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max. length of {0} should be {1}!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The min. length of {0} should be {1}!.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be latin alphanumeric..
        /// </summary>
        public static string MustBeLatinAlphanumeric {
            get {
                return ResourceManager.GetString("MustBeLatinAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National code is invalid..
        /// </summary>
        public static string NationalCodeInvalid {
            get {
                return ResourceManager.GetString("NationalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaul role is not defined..
        /// </summary>
        public static string NoDefaultRole {
            get {
                return ResourceManager.GetString("NoDefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data has been found!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify password!.
        /// </summary>
        public static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshTokenIsExpired.
        /// </summary>
        public static string RefreshTokenIsExpired {
            get {
                return ResourceManager.GetString("RefreshTokenIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshTokenIsInvalid.
        /// </summary>
        public static string RefreshTokenIsInvalid {
            get {
                return ResourceManager.GetString("RefreshTokenIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshTokenNotFound.
        /// </summary>
        public static string RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated password is invalid!.
        /// </summary>
        public static string RepeatedPasswordInvalid {
            get {
                return ResourceManager.GetString("RepeatedPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request done successfully!.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access .
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Action Access.
        /// </summary>
        public static string UnauthorizedActionAccess {
            get {
                return ResourceManager.GetString("UnauthorizedActionAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error!.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive! Contact supervisor!.
        /// </summary>
        public static string UserIsInactive {
            get {
                return ResourceManager.GetString("UserIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify username!.
        /// </summary>
        public static string UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UserNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is invalid!.
        /// </summary>
        public static string VerificationCodeInvalid {
            get {
                return ResourceManager.GetString("VerificationCodeInvalid", resourceCulture);
            }
        }
    }
}
